### Force queuing of files in the storage account
GET http://localhost:5011/queue

### Test the questions
POST http://localhost:8675/api/AskQuestions
Content-Type: application/json

{
  "question": "please summarize this document with a few sentences and a bulleted list",
  "customField": "",
  "filename": "ABC Trucking"
}

