namespace HighVolumeProcessing.UtilityLibrary
{
   public static class ConfigKeys
   {
      public const string AZURE_AISEARCH_ENDPOINT = "AZURE_AISEARCH_ENDPOINT";
      public const string AZURE_AISEARCH_INDEX_NAME = "AZURE_AISEARCH_INDEX_NAME";
      
      public const string AZURE_FOUNDRY_PROJECT_ENDPOINT = "AZURE_FOUNDRY_PROJECT_ENDPOINT";
      public const string AZURE_FOUNDRY_AGENT_ID = "AZURE_FOUNDRY_AGENT_ID";
      public const string AZURE_FOUNDRY_CHAT_DEPLOYMENT = "AZURE_FOUNDRY_CHAT_DEPLOYMENT";
      public const string AZURE_FOUNDRY_EMBEDDING_DEPLOYMENT = "AZURE_FOUNDRY_EMBEDDING_DEPLOYMENT";
      public const string AZURE_FOUNDRY_EMBEDDING_MAXTOKENS = "AZURE_FOUNDRY_EMBEDDING_MAXTOKENS";
      public const string AZURE_FOUNDRY_EMBEDDING_MODEL = "AZURE_FOUNDRY_EMBEDDING_MODEL";
      
      public const string COSMOS_ACCOUNT_ENDPOINT = "COSMOS_ACCOUNT_ENDPOINT";
      public const string COSMOS_CONTAINER_NAME = "COSMOS_CONTAINER_NAME";
      public const string COSMOS_DB_NAME = "COSMOS_DB_NAME";
     
      public const string DOCUMENT_INTELLIGENCE_ENDPOINT = "DOCUMENT_INTELLIGENCE_ENDPOINT";
      public const string DOCUMENT_INTELLIGENCE_ENDPOINTS = "DOCUMENT_INTELLIGENCE_ENDPOINTS";
      public const string DOCUMENT_INTELLIGENCE_MODEL_NAME = "DOCUMENT_INTELLIGENCE_MODEL_NAME";
     
      public const string SERVICEBUS_CONNECTION = "SERVICEBUS_CONNECTION";
      public const string SERVICEBUS_CUSTOMFIELD_QUEUE_NAME = "SERVICEBUS_CUSTOMFIELD_QUEUE_NAME";
      public const string SERVICEBUS_DOC_QUEUE_NAME = "SERVICEBUS_DOC_QUEUE_NAME";
      public const string SERVICEBUS_MOVE_QUEUE_NAME = "SERVICEBUS_MOVE_QUEUE_NAME";
      public const string SERVICEBUS_NAMESPACE_NAME = "SERVICEBUS_NAMESPACE_NAME";
      public const string SERVICEBUS_PROCESSED_QUEUE_NAME = "SERVICEBUS_PROCESSED_QUEUE_NAME";
      public const string SERVICEBUS_TOINDEX_QUEUE_NAME = "SERVICEBUS_TOINDEX_QUEUE_NAME";
      
      public const string STORAGE_ACCOUNT_NAME = "STORAGE_ACCOUNT_NAME";
      public const string STORAGE_COMPLETED_CONTAINER_NAME = "STORAGE_COMPLETED_CONTAINER_NAME";
      public const string STORAGE_PROCESS_RESULTS_CONTAINER_NAME = "STORAGE_PROCESS_RESULTS_CONTAINER_NAME";
      public const string STORAGE_SOURCE_CONTAINER_NAME = "STORAGE_SOURCE_CONTAINER_NAME";
   }
}
