namespace HighVolumeProcessing.UtilityLibrary
{
   public static class ConfigKeys
   {
      public const string APIM_SUBSCRIPTION_KEY = "APIM_SUBSCRIPTION_KEY";
      
      public const string AZURE_AISEARCH_ADMIN_KEY = "AZURE_AISEARCH_ADMIN_KEY";
      public const string AZURE_AISEARCH_ENDPOINT = "AZURE_AISEARCH_ENDPOINT";
      public const string AZURE_AISEARCH_INCLUDE_GENERAL_INDEX = "AZURE_AISEARCH_INCLUDE_GENERAL_INDEX";
      public const string AZURE_AISEARCH_INDEXNAME = "AZURE_AISEARCH_INDEXNAME";
      
      public const string AZURE_OPENAI_CHAT_DEPLOYMENT = "AZURE_OPENAI_CHAT_DEPLOYMENT";
      public const string AZURE_OPENAI_CHAT_MODEL = "AZURE_OPENAI_CHAT_MODEL";
      public const string AZURE_OPENAI_EMBEDDING_DEPLOYMENT = "AZURE_OPENAI_EMBEDDING_DEPLOYMENT";
      public const string AZURE_OPENAI_EMBEDDING_MAXTOKENS = "AZURE_OPENAI_EMBEDDING_MAXTOKENS";
      public const string AZURE_OPENAI_EMBEDDING_MODEL = "AZURE_OPENAI_EMBEDDING_MODEL";
      public const string AZURE_OPENAI_ENDPOINT = "AZURE_OPENAI_ENDPOINT";
      
      public const string COSMOS_CONNECTION = "COSMOS_CONNECTION";
      public const string COSMOS_CONTAINER_NAME = "COSMOS_CONTAINER_NAME";
      public const string COSMOS_DB_NAME = "COSMOS_DB_NAME";
     
      public const string DOCUMENT_INTELLIGENCE_ENDPOINT = "DOCUMENT_INTELLIGENCE_ENDPOINT";
      public const string DOCUMENT_INTELLIGENCE_KEY = "DOCUMENT_INTELLIGENCE_KEY";
      public const string DOCUMENT_INTELLIGENCE_MODEL_NAME = "DOCUMENT_INTELLIGENCE_MODEL_NAME";
     
      public const string SERVICEBUS_CONNECTION = "SERVICEBUS_CONNECTION";
      public const string SERVICEBUS_CUSTOMFIELD_QUEUE_NAME = "SERVICEBUS_CUSTOMFIELD_QUEUE_NAME";
      public const string SERVICEBUS_DOC_QUEUE_NAME = "SERVICEBUS_DOC_QUEUE_NAME";
      public const string SERVICEBUS_MOVE_QUEUE_NAME = "SERVICEBUS_MOVE_QUEUE_NAME";
      public const string SERVICEBUS_NAMESPACE_NAME = "SERVICEBUS_NAMESPACE_NAME";
      public const string SERVICEBUS_PROCESSED_QUEUE_NAME = "SERVICEBUS_PROCESSED_QUEUE_NAME";
      public const string SERVICEBUS_TOINDEX_QUEUE_NAME = "SERVICEBUS_TOINDEX_QUEUE_NAME";
      
      public const string STORAGE_ACCOUNT_NAME = "STORAGE_ACCOUNT_NAME";
      public const string STORAGE_COMPLETED_CONTAINER_NAME = "STORAGE_COMPLETED_CONTAINER_NAME";
      public const string STORAGE_PROCESS_RESULTS_CONTAINER_NAME = "STORAGE_PROCESS_RESULTS_CONTAINER_NAME";
      public const string STORAGE_SOURCE_CONTAINER_NAME = "STORAGE_SOURCE_CONTAINER_NAME";
   }
}
